# This is a basic workflow to help you get started with Actions

name: Get Tag

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be used for this promotion"
        required: true
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - sit
          - uat
      platform:
        description: "Platform"
        required: true
        type: choice
        options:
          - android
          - ios
          - all
      debug_mode:
        description: "Debug Mode (For Automation)"
        required: true
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ASD: ZXC

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - run: echo "${{ env.GITHUB_ENV }}"

      - run: echo "$GITHUB_ENV"
    
      - name: Get version from tag
        run: echo "KEF=AS" >> $GITHUB_ENV

      - run: echo "${{ env.KEF }}"

      - run: echo "$KEF"

      - run: echo "${{ env.ASD }}"

      - run: echo "$ASD"
    
      - name: Get version from tag
        run: echo "VERSION=$(TAG="${{ inputs.tag }}"; echo ${TAG#v} | cut -d'-' -f1,2)" >> $GITHUB_ENV

      - run: echo "${{ env.VERSION }}"

      - run: echo "${{ env.VERSIONX }}"

      - run: echo "$VERSION"

