# This is a basic workflow to help you get started with Actions

name: Get Tag

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      - name: Get version from tag
        run: echo "VERSION=$(TAG="${{ inputs.tag }}"; echo ${TAG#v} | cut -d'-' -f1,2)" >> GITHUB_ENV

      - run: echo "${{ env.VERSION }}"

      - run: echo "$VERSION"
