# This is a basic workflow to help you get started with Actions

name: Get Tag

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to be used for this promotion"
        required: true
      environment:
        description: "Environment"
        required: true
        type: choice
        default: sit
        options:
          - sit
          - uat
      platform:
        description: "Platform"
        required: true
        type: choice
        default: android
        options:
          - android
          - ios
          - all
      build_type:
        description: "Build Type"
        required: true
        type: choice
        default: release
        options:
          - release
          - debug


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ASD: ZXC

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - run: |
          echo "${{ inputs.build_type == 'debug' || 'gubed' && 'not release' }}"

