# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      flavor:
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  step1:
    # The type of runner that the job will run on
    runs-on: macos-14
    environment: playground_sit 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - run: echo $GITHUB_ENV

      - run: echo "ASD=asdasd" >> $GITHUB_ENV

      - run: cat $GITHUB_ENV

      - run: echo $ASD

      - run: echo ${{ vars.MY_VAR }}
      
          
