# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  step1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          cache: true
          flutter-version: '3.13.9'

      - run: |
          cd pubtest
          flutter pub upgrade bfi_design_system_1
      
      - uses: bluefireteam/melos-action@v2

      - run: git diff --ignore-space-at-eol --text

      - uses: actions/upload-artifact@v4
        with:
          name: pub-cache
          path: ${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}